f = open("myfile2.txt", "w")
print("file created successfully")
f.write('The file is created using python')
f.write('The file is created using python')
f.write('The file is created using python')
f.writelines('Test file is created by Python')
f.writelines('Test file is created by Python')
f.writelines('Test file is created by Python')
f.close()